export const LOADING = 'admin/products/loading'
export const ERROR = 'admin/products/error'

export const GETPRODUCTS = 'admin/getrequest'
export const GETUSERDATA = 'admin/getuserdata'
export const POSTUSERDATA = 'admin/postuserdata'
export const GETORDERSDATA = 'admin/getordersdata'
export const POSTORDERSDATA = 'admin/postordersdata'
export const DELETEPRODUCT = 'admin/deleteproduct'
export const UPDATEPRODUCT = 'admin/updateproduct'
export const ADDPRODUCT = 'admin/addproduct'
export const GETADMINSDATA = 'admin/getADMIN'
